name: CI/CD for Python Project

on:
  push:
    branches: [ main ]
  pull_request:  # Also run on pull requests
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest  # Replace with desired runner

    steps:
      - uses: actions/checkout@v4  # Checkout code

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Replace with desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Lint code
        run: flake8 .
        continue-on-error: true

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest -v automation/test_square.py

      #- name: Download artifact 
      #  uses: actions/download-artifact@v3
      #  with: 
      #    name: static-site
      - name: Archive site content 
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip 
          
      - name: Create Github release 
        id: create-new-release 
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          
      - name: Upload release asset 
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./site.zip 
          asset_name: site-v${{ github.run_number }}.zip 
          asset_content_type: application/zip 
          


      #- name: Build project (optional)
        # Add commands to build your project here (e.g., building a Docker image)
      # Deployment step (not included in this example)
      # - name: Deploy to production
      #   uses: actions/checkout@v4  # Optional, checkout code again if needed
      #   with:
      #     # ... deployment configuration options ...